### ISSUE TITLE
AWS S3 access key required

### ISSUE THREAD

**Issue by mtx-z** [h2oai/sql-sidekick#83]
Hello,

I'm trying to install your package on a fresh Ubuntu instance. 
I wonder why the make script asks me for AWS access key? I'm not planning on using AWS services. 

If it's required, what kind of key/access are required? 

Thank you for this great work.

**Comment by pramitchoudhary** [comment]
Hi, apologies for late response.
It's to access public bucket, but let try to do a better job here. Will update.

**Comment by RubenAMtz** [comment]
We realized there might be an issue by using the s3cmd cli, I will work on removing this step for the setup and make it optional.

**Comment by pramitchoudhary** [comment]
Fixed by #84
